<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="copyright">
	<div class="page-main">
	    <div class="pull-left"><span><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></span></div>
	    <div class="pull-right hidden-xs"><?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('icon_pay')->toHtml();?></div>
    </div>
</div>

