<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
$ves = $this->helper('Ves\Themesettings\Helper\Theme');
$data = $this->helper('Ves\Themesettings\Helper\Data');
$show_image = $ves->getCategoryPageCfg('general_settings/show_image');
$default_image = $ves->getCategoryPageCfg('general_settings/default_image');
$bgUrl = $data->getMediaUrl().'ves/themesettings/background/';
$default_image = $bgUrl.$default_image;
?>
<?php
    $_helper    = $this->helper('Magento\Catalog\Helper\Output');
    $_category  = $block->getCurrentCategory();
    $_imgHtml   = '';
    $_imgUrl = $_category->getImageUrl();

    if($_imgUrl == '' && $default_image!=$bgUrl){
    	$_imgUrl = $default_image;
    }

    if ($show_image && $_imgUrl) {
        $_imgHtml = '<div class="category-image"><img src="' . $_imgUrl . '" alt="' . $block->escapeHtml($_category->getName()) . '" title="' . $block->escapeHtml($_category->getName()) . '" class="image" /></div>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
        /* @escapeNotVerified */ echo $_imgHtml;
    }
?>
