<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div id="finder" class="dialogelfinder"></div>
<script type="text/javascript">
	var base_media_url = "<?php echo $this->getBaseMediaUrl() ?>";
	var base_secure_media_url = "<?php echo $this->getBaseSecureMediaUrl() ?>";
    var elfinder_connector = "<?php echo $this->getConnectorUrl(); ?>";

    require([
            'jquery',
            'Ves_BaseWidget/js/jquery/ui/jquery-ui.min',
            'Ves_BaseWidget/js/elfinder/js/elfinder.min',
        ], function(jQuery){
            console.log("\n Connector: <?php echo $this->getConnectorUrl(); ?>");
        	var f = jQuery('#finder').elfinder({
		         	url : '<?php echo $this->getConnectorUrl(); ?>'
		        }).elfinder('instance');
        });
</script>
