<?php
$ves = $this->helper("Ves\Themesettings\Helper\Theme");
$data = $this->helper("Ves\Themesettings\Helper\Data");
$enable_coppyright = $ves->getFooterCfg("general_settings/enable_coppyright");
$enable_custom_coppyright = $ves->getFooterCfg("general_settings/enable_custom_coppyright");
$custom_coppyright = $data->filter($ves->getFooterCfg("general_settings/custom_coppyright"));

?>
<?php if($enable_coppyright){ ?>
<div class="copyright">
 <?php if($enable_custom_coppyright){ ?>
 <?php echo $custom_coppyright; ?>
 <?php }else{ ?> 
 <div class="page-main">
	    <div class="pull-left"><span><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></span></div>
	    <div class="pull-right hidden-xs"><?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('pencil-icon_pay')->toHtml();?></div>
 </div>
 <?php } ?>    
</div>
<?php } ?>