<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
// Ves
$_imgHelper = $this->helper('Ves\Themesettings\Helper\Image');
$data = $this->helper('Ves\Themesettings\Helper\Data'); 
$ves = $this->helper('Ves\Themesettings\Helper\Theme');

$classes = '';

// Item Settings
$show_name = $ves->getProductListingCfg('product_settings/show_name');
$show_name_single_line = (int)$ves->getProductListingCfg('product_settings/show_name_single_line');
if($show_name_single_line){
    $classes .= ' single-line-name';
}
$show_short_description = $ves->getProductListingCfg('product_settings/show_short_description');
$short_max_char = (int)$ves->getProductListingCfg('product_settings/short_max_char');
$show_learnmore = $ves->getProductListingCfg('product_settings/show_learnmore');
$show_price = $ves->getProductListingCfg('product_settings/show_price');
$show_review = $ves->getProductListingCfg('product_settings/show_review');
$show_countdowntimer = $ves->getProductListingCfg('product_settings/show_countdowntimer');
$show_quickview = $ves->getProductListingCfg('product_settings/show_quickview');
$quickview_popup_height = $ves->getProductListingCfg('product_settings/quickview_popup_height');
$quickview_popup_width = $ves->getProductListingCfg('product_settings/quickview_popup_width');
$show_addtocart = $ves->getProductListingCfg('product_settings/show_addtocart');
$addtocart_popup_height = $ves->getProductListingCfg('product_settings/addtocart_popup_height');
$addtocart_popup_width = $ves->getProductListingCfg('product_settings/addtocart_popup_width');
$show_wishlist = $ves->getProductListingCfg('product_settings/show_wishlist');
$show_compare = $ves->getProductListingCfg('product_settings/show_compare');
$show_new_label = $ves->getProductListingCfg('product_settings/show_new_label');
$show_sale_label = $ves->getProductListingCfg('product_settings/show_sale_label');
$show_image = $ves->getProductListingCfg('product_settings/show_image');
$aspect_ratio = $ves->getProductListingCfg('product_settings/aspect_ratio');
$image_width = $ves->getProductListingCfg('product_settings/image_width');
$image_height = $ves->getProductListingCfg('product_settings/image_height');
$alt_image = $ves->getProductListingCfg('product_settings/alt_image');
$alt_image_column = $ves->getProductListingCfg('product_settings/alt_image_column');
$alt_image_column_value = $ves->getProductListingCfg('product_settings/alt_image_column_value');

//If image width is not specified, use default values
if ($image_width <= 0){
    $image_width = 300;
    $image_height = 300;
}
$catViewKeepFrame = TRUE;
if($aspect_ratio){
    $image_height = 0;
    $catViewKeepFrame = FALSE;
}
if ($data->getCoreRegistry()->registry('catViewKeepFrame') === NULL){
    $data->getCoreRegistry()->register('catViewKeepFrame', $catViewKeepFrame);
}

?>


<?php if (($_products = $block->getProductCollection()) && $_products->getSize()): ?>
    <div class="block widget block-new-products-list">
        <div class="block-title">
            <strong><?php /* @escapeNotVerified */ echo __('New Products') ?></strong>
        </div>
        <div class="block-content">
            <?php $suffix = $block->getNameInLayout(); ?>
            <?php $iterator = 1; ?>
            <ol class="product-items <?php echo $classes ?>" id="widget-new-products-<?php /* @escapeNotVerified */ echo $suffix; ?>">
                <?php foreach ($_products->getItems() as $_product): ?>
                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                    <div class="product-item-info">
                        <?php // Product Image ?>
                        <?php if($show_image){ ?>
                        <?php
                        $_image = $_imgHelper->getImg($_product, $image_width, $image_height, 'category_page_grid');
                        ?>
                        <?php if($_image){ ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_image->getLabel() ?>" class="product-item-photo">
                            <img src="<?php echo $_image->getUrl(); ?>" alt="<?php echo $_image->getLabel() ?>" />
                        </a>
                        <?php } ?>
                        <?php if($alt_image){ ?>
                        <?php
                        $_altImg = $_imgHelper->getAltImgHtml($_product, $image_width, $image_height, 'category_page_grid', $alt_image_column, $alt_image_column_value);
                        ?>
                        <?php if($_altImg){ ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" class="hover-image" title="<?php echo $_altImg->getLabel() ?>" class="hover-image">
                            <img src="<?php echo $_altImg->getUrl(); ?>" alt="<?php echo $_altImg->getLabel() ?>" />
                        </a>
                        <?php } ?>
                        <?php } ?>
                        <?php } ?>

                        <div class="product-item-details">
                            <?php if($show_name){ ?>
                            <strong class="product-item-name">
                                <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>"
                                   title="<?php /* @escapeNotVerified */ echo $block->stripTags($_product->getName(), null, true) ?>)" class="product-item-link">
                                    <?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Output')->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>
                            </strong>
                            <?php } ?>
                            <?php /* @escapeNotVerified */ echo $block->getProductPriceHtml($_product, '-widget-new-' . $suffix) ?>
                            <div class="product-item-actions">
                                <?php if ($show_addtocart): ?>
                                            <div class="actions-primary">
                                                <?php if ($_product->isSaleable()): ?>
                                                    <?php if ($_product->getTypeInstance()->hasRequiredOptions($_product)): ?>
                                                        <button class="action tocart primary add-to-cart vesthemesettings-fancybox" type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>" data-fancybox-href="<?php echo $data->getAddToCartUrl($_product) ?>" data-fancybox-type="iframe" data-fancybox-width="<?php echo $addtocart_popup_width ?>" data-fancybox-height="<?php echo $addtocart_popup_height ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php else: ?>
                                                        <?php
                                                            $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_product), ['product' => $_product->getEntityId()])
                                                        ?>
                                                        <button class="action tocart primary" data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php endif; ?>
                                                <?php else: ?>
                                                    <?php if ($_product->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                            </div>
                        </div>
                    </div>
                    <?php echo($iterator == count($_products->getItems())+1) ? '</li>' : '' ?>
                <?php endforeach; ?>
            </ol>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif; ?>
