<?php 
 /*------------------------------------------------------------------------
  # VenusTheme Block Builder Module 
  # ------------------------------------------------------------------------
  # author:    VenusTheme.Com
  # copyright: Copyright (C) 2012 http://www.venustheme.com. All Rights Reserved.
  # @license: http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL
  # Websites: http://www.venustheme.com
  # Technical Support:  http://www.venustheme.com/
-------------------------------------------------------------------------*/

$themeName = "default";
$path_to_pattern = $this->getBlockHelper()->getConfig("general/path_to_pattern", null, "pagebuilder/livecss/images/patterns", "veslivecss");
$pattern_folder_path = str_replace("/", DIRECTORY_SEPARATOR, $path_to_pattern);// pub/pagebuilder/livecss/images/patterns/
$pattern_base_url = $this->getBaseUrl().'pub/'.$path_to_pattern.'/';

$path_css_profile = $this->getBlockHelper()->getConfig("general/path_css_profile", null, "media/pagebuilder/livecss", "veslivecss");
$custom_css_folder_path = str_replace("/", DIRECTORY_SEPARATOR, $path_css_profile);// pub/pagebuilder/livecss/customize/

$patterns =  $this->getPattern( $pattern_folder_path );

$border_styles = [		"hidden", 
						"dotted", 
						"dashed", 
						"solid", 
						"double", 
						"groove", 
						"ridge", 
						"inset", 
						"outset", 
						"initial",
						"inherit"];


$allow_save_editor = $this->getBlockHelper()->getConfig("general/allow_save_profile", null, "0", "veslivecss");
$allow_current_ip = $this->isAllowCurrentIp();
?>

<div id="ves-livecss" class="hidden-md hidden-sm hidden-xs">
	<div class="ves-paneltool editortool">
		<div class="panelbutton">
			<i class="fa fa-cog"></i>
		</div>

		<div class="panelcontent editortool">
			<div class="panelinner">
				<form action="<?php echo $this->getLiveEditLink(); ?>" enctype="multipart/form-data" method="post" class="clearfix" id="ves_pagebuilder_livecss_form">
					<h4><?php echo __( 'Live Css Editor' ); ?></h4>					
					<?php $xmlselectors = $this->renderEditorThemeForm( );?>
					<?php if($allow_save_editor && $allow_current_ip): ?>
						<?php
					 		$themeCustomizePath = $this->getCustomizePath( $custom_css_folder_path );

					 		$files = $this->getFileList( $themeCustomizePath , '.css' );
						?>
						<p>
							<span class="badge"><?php echo __("Theme: ");?>: <?php echo $themeName; ?></span>
						</p>	 	

						<div class="buttons-group">
							<input type="hidden" name="action-mode" id="ves-action-mode" >
							<input type="hidden" name="liveeditor" value="1">
							<input type="hidden" name="save_path" value="<?php echo $custom_css_folder_path; ?>">
							<input type="hidden" name="pattern_base_url" value="<?php echo $pattern_base_url; ?>">
							<a href="#" class="btn btn-primary btn-xs" onclick="jQuery('#ves-action-mode').val('save-edit');jQuery('#ves_pagebuilder_livecss_form').submit();"><?php echo __('Save Profile');?></a>
							<a href="#" class="btn btn-danger btn-xs" onclick="jQuery('#ves-action-mode').val('save-delete');jQuery('#ves_pagebuilder_livecss_form').submit();"><?php echo __('Delete');?></a>
						</div>

						<div class="groups form-fluid" style="width: 100%">
							<div class="form-group pull-left" style="width:45%">
								<label><?php echo __('Css Profiles: '); ?></label>	
								<select name="saved_file" id="ves-saved-files">
									<option value=""> ------------- </option>
									<?php foreach( $files as $file ){ $file = str_replace( ".css","", $file); ?>
										<option value="<?php echo $file;?>"><?php echo $file; ?></option>
									<?php } ?>
								</select> 
							</div>

							<div class="form-group pull-left" style="width:45%">
								<label class="show-for-notexisted"><?php echo __('And Named This:'); ?></label>
								<label class="show-for-existed"><?php echo __('Rename This'); ?></label>
								<input type="text" name="newfile" />
								
							</div>	
					    </div>
					<?php endif; ?>

				    <div class="clearfix panel-group" id="ves-customize-body">
						<ul class="nav nav-tabs" id="ves-pagesbuilder-livecss-tab">
							<?php foreach( $xmlselectors as $for => $output ) { ?>
							<li><a href="#ves-livecss-tab-<?php echo $for ?>"><?php echo __(ucfirst($for) );?></a></li>		
							<?php } ?>
						</ul>

						<div class="tab-content"> 
						<?php foreach( $xmlselectors as $for => $output ) { ?>
							<div class="tab-pane" id="ves-livecss-tab-<?php echo $for; ?>">
								<?php if( !empty( $output) ){?>
								<div class="accordion">
								<?php $i=0; foreach ( $output as $group ) { ?>
								    <div class="accordion-group  panel panel-default clearfix">
										<div class="accordion-heading panel-heading">
											<a class="accordion-toggle" data-toggle="collapse" data-parent="#custom-accordion" href="#collapse<?php echo $group['match'];?>">
												<?php echo $group['header']; ?>	 
											</a>
										</div>

										<div id="collapse<?php echo $group['match'];?>" class="accordion-body panel-collapse collapse <?php if( $i++ ==0) { ?> in <?php } ?>">
											<div class="accordion-inner panel-body clearfix">
												<?php foreach ($group['selector'] as $k => $item ) {  ?>
												<?php  if (isset($item['type'])&&$item['type']=="image") { ?>
												<div class="form-group background-images"> 
													<label data-tooltip="true" data-placement="top" title="<?php echo __("Css Selector: ")." ".$item['selector']; ?>"><?php echo $item['label']?></label>
													<a class="clear-bg label label-success" href="#">Clear</a>
													<input value="" name="customize[<?php echo $group['match'];?>][]" data-match="<?php echo $group['match'];?>" type="text" class="input-setting input-background-setting" data-selector="<?php echo $item['selector']?>" data-attrs="background-image" data-image="">
													<div class="clearfix"></div>
													<p><em style="font-size:10px"><?php echo __('Those Images in folder pub/pagebuilder/livecss/images/patterns/');?></em></p>
													<div class="bi-wrapper clearfix">
														<?php foreach ( $patterns as $pattern ){ ?>
														<div style="background:url('<?php echo $pattern_base_url.$pattern;?>') no-repeat center center;" class="pull-left" data-image="<?php echo $pattern_base_url.$pattern;?>" data-val="<?php echo $pattern_base_url.$pattern; ?>"></div>
														<?php } ?>
													</div>
												</div>
											
												<?php } elseif( $item['type'] == "fontsize" ) { ?>
												<div class="form-group">
													<label data-tooltip="true" data-placement="top" title="<?php echo __("Css Selector: ")." ".$item['selector']; ?>"><?php echo $item['label']?></label>
													<select name="customize[<?php echo $group['match'];?>][]" data-match="<?php echo $group['match']?>" class="input-setting" data-selector="<?php echo $item['selector']?>" data-attrs="<?php echo $item['attrs']?>">
														<option value=""><?php echo __('Inherit'); ?></option>


														<?php for( $fs=1; $fs<=32; $fs++ ) { ?>
														<option value="<?php echo $fs; ?>"><?php echo $fs; ?></option>
														<?php } ?>
													</select>	
													<a href="#" class="clear-bg label label-success"><?php echo __('Clear');?></a>
												</div>

										  		<?php } elseif( $item['type'] == "borderstyle" ) { ?>
				                                   <div class="form-group">
					                                   <label data-tooltip="true" data-placement="top" title="<?php echo __("Css Selector: ")." ".$item['selector']; ?>"><?php echo $item['label']?></label>
					                                  	<select name="customize[<?php echo $group['match'];?>][]" data-match="<?php echo $group['match']?>" class="input-setting" data-selector="<?php echo $item['selector']?>" data-attrs="<?php echo $item['attrs']?>">
															<option value=""><?php echo __('None'); ?></option>
															<?php foreach ( $border_styles as $item ){ ?>
															<option value="<?php echo $item; ?>"><?php echo $item; ?></option>
															<?php } ?>
														</select>	
														<a href="#" class="clear-bg label label-success"><?php echo __('Clear');?></a>
				                                    </div>

				                                    <?php } elseif( $item['type'] == "text" ) { ?>
				                                    <div class="form-group">
														<label data-tooltip="true" data-placement="top" title="<?php echo __("Css Selector: ")." ".$item['selector']; ?>"><?php echo $item['label']?></label>
														<input value="" size="10" name="customize[<?php echo $group['match']?>][]" data-match="<?php echo $group['match']?>" type="text" class="input-setting color-selector" data-selector="<?php echo $item['selector']?>" data-attrs="<?php echo $item['attrs']?>">
														<a href="#" class="clear-bg label label-success"><?php echo __('Clear');?></a>
												    </div>

				                                    <?php } elseif( $item['type'] == "raw-text" ) { ?>
					                                <div class="form-group">
														<label data-tooltip="true" data-placement="top" title="<?php echo __("Css Selector: ")." ".$item['selector']; ?>"><?php echo $item['label']?></label>
														<input value="" size="10" name="customize[<?php echo $group['match']?>][]" data-match="<?php echo $group['match']?>" type="text" style="color:#000" class="input-setting input-text" data-selector="<?php echo $item['selector']?>" data-attrs="<?php echo $item['attrs']?>">
														<a href="#" class="clear-bg label label-success"><?php echo __('Clear');?></a>
													</div>

													<?php } elseif( $item['type'] == "textarea" ) { ?>
					                                <div class="form-group">
														<label data-tooltip="true" data-placement="top" title="<?php echo __("Css Selector: ")." ".$item['selector']; ?>"><?php echo $item['label']?></label>
														<textarea rows="5" name="customize[<?php echo $group['match']?>][]" data-match="<?php echo $group['match']?>" style="color:#000" class="textarea-setting custom-css" data-selector="<?php echo $item['selector']?>" data-attrs="<?php echo $item['attrs']?>" placeholder="<?php echo __("Write your custom rules..."); ?>" data-index="<?php echo $k; ?>"></textarea>
														<a href="#" class="clear-bg label label-success"><?php echo __('Clear');?></a>
														<script type="text/javascript"><!--
															jQuery(document).ready(function($) {
																var a = "vescustomcss-<?php echo $k; ?>";
																var csslink = $("#"+a);

																if(csslink.length <= 0) {
																	csslink = $('<style type="text/css" rel="stylesheet" id="' + a + '" />').appendTo("head");
																}
															})
														//-->
														</script>
													</div>

													<?php } else { ?>
													<div class="form-group">
														<label data-tooltip="true" data-placement="top" title="<?php echo __("Css Selector: ")." ".$item['selector']; ?>"><?php echo $item['label']?></label>
														<input value="" size="10" name="customize[<?php echo $group['match']?>][]" data-match="<?php echo $group['match']?>" type="text" class="input-setting color-selector" data-selector="<?php echo $item['selector']?>" data-attrs="<?php echo $item['attrs']?>">
														<a href="#" class="clear-bg label label-success"><?php echo __('Clear');?></a>
													</div>
													<?php } ?>
											 	<?php } ?>
										    </div>
										</div>
									</div>          	
								<?php } ?>
								</div>
							<?php } ?>
						</div>
					    <?php } /* endforeach  */?>
						</div>   
					</div>
				</form>		    
			</div>		
		</div>
		<div class="panelbutton label-customize"></div>
	</div>
</div> 

<script type="text/javascript">

require([
        'jquery',
        'Ves_BaseWidget/js/bootstrap336/bootstrap.min',
        'Ves_BaseWidget/js/colorpicker/js/colorpicker'
        ],function($){
			$(".ves-paneltool .panelbutton").click( function(){	
				$(this).parent().toggleClass("active");
			} );

			$('#ves-pagesbuilder-livecss-tab a').click(function (e) {
				e.preventDefault();
				$(this).tab('show');
			})
			$('#ves-pagesbuilder-livecss-tab a:first').tab('show'); 


			var $VESMAINCONTAINER = $("html");

			/**
			 * BACKGROUND-IMAGE SELECTION
			 */
			$(".background-images").each( function(){

				var $parent = this;
				var $input  = $(".input-background-setting", $parent ); 
				$(".bi-wrapper > div",this).click( function(){
					 $input.val( $(this).data('val') ); 
					 $('.bi-wrapper > div', $parent).removeClass('active');
					 $(this).addClass('active');

					 if( $input.data('selector') ){  
						$($input.data('selector'), $($VESMAINCONTAINER) ).css( $input.data('attrs'),'url('+ $(this).data('image') +')', 'important' );
					 }
				} );
			} );

			$(".clear-bg").click( function(){
					var $parent = $(this).parent();
					var $input  = $(".input-setting", $parent );
					if($input.length > 0) {
						if( $input.val('') ) {
							if( $parent.hasClass("background-images") ) {
								$('.bi-wrapper > div',$parent).removeClass('active');	
								$($input.data('selector'),$("#main-preview iframe").contents()).css( $input.data('attrs'),'none' );
							}else {
								$input.attr( 'style','' )	
							}
							$($input.data('selector'), $($VESMAINCONTAINER) ).css( $input.data('attrs'),'inherit' );

						}	
						$input.val('');
					} else {
						$input  = $(".textarea-setting", $parent );
						var index = $input.data("index");

						if($input.val('') && $("#vescustomcss-"+index).length > 0) {
							$("#vescustomcss-"+index).text('');
						}
						$input.val('');
					}
					

					return false;
		} );

		$('.accordion-group textarea.textarea-setting').keyup( function() {
				var input = this;
				var index = $(input).data("index");

				if( $(input).data('selector') && $("#vescustomcss-"+index).length > 0){

					$("#vescustomcss-"+index).text($(input).data('selector') + "{" + $(input).val() + "}");

				}
		})

		// Color selector
		 $('.accordion-group input.color-selector').each( function(){
			 	 var input = this;
			 	 $(input).attr('readonly','readonly');
			 	 $(input).ColorPicker({
			 	 	onChange:function (hsb, hex, rgb) {
			 	 		$(input).css('backgroundColor', '#' + hex);
			 	 		$(input).val( hex );

			 	 		if( $(input).data('selector') ){
			 	 			if("body" == $(input).data('selector') ) {
			 	 				$($(input).data('selector')).css( $(input).data('attrs'),"#"+$(input).val())
			 	 			} else {
			 	 				$($(input).data('selector')).css( $(input).data('attrs'),"#"+$(input).val())
			 	 			}
							
						}
			 	 	}
			 	 });
		 	} );

		//Input text 
		$('.accordion-group input.input-text').keyup( function() {
				var input = this;
				if( $(input).data('selector') ){   
					$($(input).data('selector')).css( $(input).data('attrs'), $(input).val() )
				}
			})

		//Select value 
		$('.accordion-group select.input-setting').change( function(){
			var input = this; 
				if( $(input).data('selector') ){  
				var ex = $(input).data('attrs')=='font-size'?'px':"";
				$($(input).data('selector')).css( $(input).data('attrs'), $(input).val() + ex);
			}
		 } );

		<?php if($allow_save_editor): ?>
		/**
		 *  FORM SUBMIT
		 */
		 $( "#ves_pagebuilder_livecss_form" ).submit( function(){ 
			$('.input-setting').each( function(){
				if( $(this).data("match") ) {
					var val = $(this).data('selector')+"|"+$(this).data('attrs');
					$(this).parent().append('<input type="hidden" name="customize_match['+$(this).data("match")+'][]" value="'+val+'"/>');
				}	 
			} );

			$('.textarea-setting').each( function(){
				if( $(this).data("match") ) {
					var val = $(this).data('selector')+"|customcss";
					$(this).parent().append('<input type="hidden" name="customize_match['+$(this).data("match")+'][]" value="'+val+'"/>');
				}	 
			} );

			return true; 
		} );

		$(".show-for-existed").hide();

		if($('#loaded_custom_css_profile').length > 0) {
			$('#loaded_custom_css_profile').data("backhref", $('#loaded_custom_css_profile').attr("href"));
		}
		//Saved files changes
		$("#ves-saved-files").change( function() {

			if( $(this).val() ){  
				$(".show-for-notexisted").hide();
				$(".show-for-existed").show();
			}else {
				$(".show-for-notexisted").show();
				$(".show-for-existed").hide();
			}
			if("" != $(this).val()) {

				var url  = '<?php echo $this->getCustomizeFolderURL(); ?>'+$(this).val()+".json?rand"+Math.random();

				$.getJSON( url, function(data) {
					var items = data;
						if( items ){
							if($('#loaded_custom_css_profile').length > 0) {
								$('#loaded_custom_css_profile').attr("href", "");
							}
							$('#ves-customize-body .accordion-group').each( function(){
								var i = 0;
								$("input, select, textarea", this).each( function(){
									if( $(this).data('match') ){
										if( items[$(this).data('match')] && items[$(this).data('match')][i] ){ 
											var el = items[jQuery(this).data('match')][i];
										 	$(this).val( el.val );
										 	if( el.val== '') {
										 		$(this).css('background',"inherit");
										 	}
										 	else { 
										 		$(this).css('background',"#"+el.val);
										 	}
										 	$(this).ColorPickerSetColor(el.val );
										 	/*Set css property for elements*/
										 	if( $(this).data('selector') && (el.val || el.val.length > 0)){
										 		if($(this).hasClass("color-selector")) {
										 			$($(this).data('selector')).css( $(this).data('attrs'),"#"+$(this).val());

										 		} else if($(this).hasClass("input-background-setting")) {

										 			$($(this).data('selector')).css( $(this).data('attrs'), 'url('+ $(this).val() +')', 'important' );

											 	} else if($(this).hasClass("input-text")) {

										 			$($(this).data('selector')).css( $(this).data('attrs'),"#"+$(this).val() );

										 		} else if($(this).hasClass("input-setting")) {

										 			var ex = $(this).data('attrs')=='font-size'?'px':"";

													$($(this).data('selector')).css( $(this).data('attrs'), $(this).val() + ex);

										 		} else if($(this).hasClass("textarea-setting")) {

										 			var index = $(this).data('index');

										 			if($("#vescustomcss-"+index).length > 0 ) {
										 				$("#vescustomcss-"+index).text( $(this).data('selector') + "{" + $(this).val() + "}" );
										 			}
													

										 		}
											}
										}

										i++;
									}
								} );
								 
							});
						}
					})
			} else {
				if($('#loaded_custom_css_profile').length > 0) {
					$('#loaded_custom_css_profile').attr("href", $('#loaded_custom_css_profile').data("backhref"));
				}
			}
		});
		<?php endif; ?>
} );

</script>
