<?php
$id = rand().time();
$all_helper = $this->helper("Ves\All\Helper\Data");
$active = isset($active)?$active:0;
if (isset($accordions)): ?>
<div class="ves-widget widget-accordion block <?php echo $addition_cls; ?> <?php if (isset($stylecls)&&$stylecls) echo 'block-'.$stylecls;?>">
	<?php if (isset($widget_heading)&&!empty($widget_heading)): ?>
	<div class="block-title">
		<strong><span><?php echo $widget_heading; ?></span></strong>
	</div>
	<?php endif; ?>
	<div class="widget-inner block-content">	
		<div id="accordion<?php echo $id; ?>" class="panel-group">
	 	<?php foreach ($accordions as $key => $ac): ?>
		
				<div class="panel panel-default">
				  <div class="panel-heading">
				    <h4 class="panel-title">
				      <a href="#collapseAc<?php echo $id.$key;?>" onclick="return false;" data-parent="#accordion<?php echo $id; ?>" data-toggle="collapse" class="accordion-toggle collapsed">
				       	<?php echo $ac['header']; ?> 
				      </a>
				    </h4>
				  </div>
				  <div class="panel-collapse collapse <?php if ($key==$active) echo  'in'; else echo 'out';?>" id="collapseAc<?php echo $id.$key;?>"  >
				    <div class="panel-body">
				     <?php echo $ac['content']; ?>
				    </div>
				  </div>
				</div>
			
	 	<?php endforeach; ?>
		</div>	
	</div>
</div>
<script type="text/javascript">
	require([
		'jquery'
		<?php if($all_helper->getConfig("enable_bootstrap_js")): ?>
		,"Ves_All/lib/bootstrap/js/bootstrap.min"
		<?php endif; ?>
		],function($){
			
		});
</script>
<?php endif; ?>


