<?php
/*
* Pts Prestashop Theme Framework for Prestashop 1.6.x
*
* @package   ptspagebuilder
* @version   5.0
* @author    http://www.prestabrain.com
* @copyright Copyright (C) October 2013 prestabrain.com <@emai:prestabrain@gmail.com>
*               <info@prestabrain.com>.All rights reserved.
* @license   GNU General Public License version 2
*/

if (isset($html)&& !empty($html)): ?>
<div class="ves-widget alert alert-dismissable <?php echo $alert_type; ?> <?php echo $addition_cls; ?>">
	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
	<?php echo $html; ?>
</div>
<script type="text/javascript">
require(['jquery'],function($){
    $(document).ready(function(){
	require([
		'jquery',
		<?php if($this->helper("Ves\All\Helper\Data")->getConfig("enable_bootstrap_js")): ?>
		,"Ves_All/lib/bootstrap/js/bootstrap.min"
		<?php endif; ?>
		],function($){
			
		});
	});
});
</script>
<?php endif; ?>