<?php 
$_catalogCatgoryHelper = $this->helper('Magento\Catalog\Helper\Category');
$moduleId = rand().time();
$catIds = explode(',', $catsid);
$cols = (isset($cols) && $cols)?(int)$cols:4;
$item_cols = round(12/$cols);
$auto_play_mode = (int)$autoplay;
$auto_play = $auto_play_mode?"true":"false";
$cms = isset($cms)?$cms:"";
$show_title = $this->getConfig("show_title", 1);

?>
<div class="ves-widget widget-categories-info block <?php echo $addition_cls; ?> <?php if (isset($stylecls)&&$stylecls) echo 'block-'.$stylecls;?>">
		<ul>
			<?php 

				if($catIds ){
					$number_check_limit = 1;
					?>
					<?php foreach($catIds as $catId): 
						$category = $this->getCategoryInfo($catId); 
						if(!$category || !$_catalogCatgoryHelper->canShow($category))
							continue;
					?>
						<li>
							<?php if( $show_title ){ ?>
							<a href="<?php echo $_catalogCatgoryHelper->getCategoryUrl($category)?>" title="<?php echo $category->getName()?>">
								<?php echo $category->getName()?>
								<?php if($enable_numbproduct): ?>
									(<?php echo $category->getProductCount() ?>)
								<?php endif; ?>
							</a>
							<?php } ?>
							<?php if( $enable_image && $category->getImage()){ ?>
							<div class="image">
								<a href="<?php echo $_catalogCatgoryHelper->getCategoryUrl($category)?>" title="<?php echo $category->getName()?>">
									<?php 
										$category_image = $this->getCategoryImage( $category, $image_width, $image_height);
									?>
									<img src="<?php echo $category_image; ?>" width="<?php echo (int)$image_width;?>" height="<?php echo (int)$image_height;?>" alt="<?php echo $category->getName()?>">
								</a>
							</div>
							<?php } ?>
						</li>
					
				<?php $number_check_limit ++ ?>
			<?php endforeach; ?>
			<?php } ?>
			<!-- Show pretext -->
			<?php if($pretext && !$cms ) { ?>
			<li class="pretext"><?php echo $pretext;?></li>
			<?php } elseif($cms) { ?>
			<li class="pretext"><?php echo $cms;?></li>
			<?php } ?>
			<!-- End Show pretext -->
		</ul>

</div>
