<?php if($number): ?>
<?php $blockId = rand().time(); ?>
<div class="ves-widget widget-counters counters">
   <div class="counter-wrap <?php if (isset($stylecls)&&$stylecls) echo 'text-'.$stylecls;?>" style="<?php echo (isset($font_size) && $font_size)?'font-size:'.$font_size:''; ?>">

    <?php if($icon): ?>
    <i class="fa <?php echo $icon; ?>" style="<?php echo (isset($font_size) && $font_size)?'font-size:'.$font_size:''; ?>"></i><br>
    <?php endif; ?>

    <span id="counter<?php echo $blockId ?>" class="counter"><?php echo (int)$number; ?></span></div>

    <?php if (isset($title)&&!empty($title)): ?>
    <h5><?php echo $title; ?></h5>
  <?php endif; ?>

  <?php if (isset($description)&&!empty($description)): ?>
    <div class="description"><?php echo $description; ?></div>
  <?php endif; ?>
</div>

<script type="text/javascript">
require(['jquery'],function($){
    $(document).ready(function(){
      require([
        'jquery',
        <?php if($this->helper("Ves\All\Helper\Data")->getConfig("enable_bootstrap_js")): ?>
        ,"Ves_All/lib/bootstrap/js/bootstrap.min"
        <?php endif; ?>
        ],function($){
          $('#counter<?php echo $blockId ?>').each(function() {

            $(this).animate({countNum: $(this).text()}, {
              duration: <?php echo $speed?(int)$speed:8000; ?>,
              easing:'linear',
              step: function() {
                $(this).text(Math.floor(this.countNum));
              },
              complete: function() {
                $(this).text(this.countNum);
              }
            });
          });
        });
   });
});
</script>
<?php endif; ?>