<?php
	$modid = rand().time();
	$enable_collapse = $this->getConfig("enable_collapse", 0);
?>
<div class="ves-widget block block-list block-facebook-widget">
	<?php if(trim($title)!=''): ?>
		<div class="block-title">
			<?php if($enable_collapse): ?><span class="opener hidden-lg hidden-md" data-toggle="collapse" data-target="#widget-facebook<?php echo $modid; ?>"><i class="fa fa-angle-down"></i></span><?php endif; ?>
			<strong><span><?php echo $title; ?></span></strong>
		</div>
	<?php endif; ?>
	<div id="widget-facebook<?php echo $modid; ?>" class="widget-inner block-content <?php if($enable_collapse): ?> widget-enanle-collapse collapse in <?php endif; ?>">

		<div id="fb-root"></div>
		<script>(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.4&appId=<?php echo $app_id; ?>";
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));</script>

		<div class="fb-comments" data-href="<?php echo $url; ?>" data-width="<?php echo (int)$width; ?>" data-numposts="<?php echo (int)$number_posts; ?>" data-colorscheme="<?php echo $theme; ?>" data-order-by="<?php echo $order_by; ?>"></div>

				
	</div>
</div>
<?php if($enable_collapse): ?>
<script type="text/javascript">
require(['jquery'],function($){
    $(document).ready(function(){
	require([
		'jquery'
		<?php if($this->helper("Ves\All\Helper\Data")->getConfig("enable_bootstrap_js")): ?>
		,"Ves_All/lib/bootstrap/js/bootstrap.min"
		<?php endif; ?>
		],function($){
			
		});
	});
});
</script>
<?php endif; ?>