<?php
$title = $this->getData('title');
$form_widget_type = $this->getData('form_type');
$class = $this->getData('addition_class');
$expire = (int)$this->getData('expire');
$id = rand().time();
$cookie_name = 'widget-popup-'.$form_widget_type;
$delay = (int)$this->getData('delay');
//Convert from seconds to milliseconds
$delay = $delay*1000;
$width = $this->getData('popup_width');
$height = $this->getData('popup_height');
$opacity = $this->getData('opacity');
$open_button_text = $this->getConfig('open_button_text', '');
$button_class = $this->getConfig('button_class', '');
$open_popup_first = $this->getConfig('open_popup_first', 1);
$show_disable_option = $this->getConfig('show_disable_option', 1);
$responsive_popup = $this->getConfig('responsive_popup', 0);
?>

<?php if(isset($html) && $html!= ''){ ?>
<?php if($open_button_text): ?>
	<a href="javascript:void(0);" onclick="return showPopup<?php echo $id ?>();" class="<?php echo $button_class; ?>"><?php echo $open_button_text; ?></a>
<?php endif; ?>
<div class="ves-widget widget-popup" id="widget-popup-<?php echo $form_widget_type; ?>" style="display:none">
	<?php echo $html; ?>
	<?php if($show_disable_option): ?>
	<div class="clear">
		<div class="action_button">
	        <input type="checkbox" class="hide-popup-action" data-cookiename="<?php echo $cookie_name; ?>" name="action" id="action-position-<?php echo $form_widget_type; ?>" value="hide">
	        <label class="checkbox-inline" for="action-position-<?php echo $form_widget_type; ?>"><?php echo __("Not receive this message again"); ?></label>
	    </div>
	</div>
	<?php endif ; ?>
</div>
<script type="text/javascript">
function showPopup<?php echo $id ?>(){
	if(jQuery.cookie("<?php echo $cookie_name; ?>") == 'null' || jQuery.cookie("<?php echo $cookie_name; ?>") != "true"){
		var cboxOptions = {
				width: "<?php echo $width ?>",
			  	maxWidth: '960px',
			  	maxHeight: '960px',
			  	initialWidth: 300,
			  	initialHeight: 100
			}

			if(window.innerWidth > 780){
				cboxOptions.initialWidth = 600;
				cboxOptions.initialHeight = 450;
			}

			jQuery.colorbox({
				inline:true,
				href:'#widget-popup-<?php echo $form_widget_type; ?>',
				<?php if($responsive_popup): ?>
				maxWidth: '960px',
			  	maxHeight: '960px',
			  	initialWidth: cboxOptions.initialWidth,
			  	initialHeight: cboxOptions.initialHeight,
				<?php endif; ?>
				width: "<?php echo $width ?>",
				/*height: "<?php echo $height ?>",*/
				opacity: <?php echo $opacity ?>,
				<?php if($title != ''){ ?>
					title:"<?php echo $title ?>",
				<?php } ?>
				onLoad:function(){

						<?php if($expire && $expire>0){ ?>
							// expires after number second
							var date = new Date();
							var second_number = <?php echo $expire  ?>;
							date.setTime(date.getTime() + (second_number * 1000));
							jQuery.cookie("<?php echo $cookie_name; ?>", "true", { expires: date });
							<?php } ?>

							jQuery('#widget-popup-<?php echo $form_widget_type; ?>').show();
							<?php if($class != ''){ ?>
								jQuery("#colorbox").addClass("<?php echo $class; ?>");
								<?php } ?>
							},
				onClosed:function(){
								jQuery('#widget-popup-<?php echo $form_widget_type; ?>').hide();
								<?php if($class != ''){ ?>
								jQuery("#colorbox").removeClass("<?php echo $class; ?>");
								<?php } ?>
								}
			});
			if(jQuery(".hide-popup-action").length > 0) {
				jQuery(".hide-popup-action").on('change', function() {
					var cookie_name = jQuery(this).data("cookiename");
					if(cookie_name && ("hide" == jQuery(this).val())) {
						jQuery.cookie(cookie_name, "true");
					}
				});
			}
			<?php if($responsive_popup): ?>
			jQuery(window).resize(function(){
			    jQuery.colorbox.resize({
			      width: window.innerWidth > parseInt(cboxOptions.maxWidth) ? cboxOptions.maxWidth : cboxOptions.width
			    });
			});
			<?php endif; ?>
	}

}
require(['jquery'],function($){
            $(document).ready(function(){
            	require([
						'jquery',
						'jquery/jquery.cookie'
						<?php if($this->helper("Ves\All\Helper\Data")->getConfig("enable_colorbox")): ?>
					    ,"Ves_All/lib/colorbox/jquery.colorbox.min"
					    <?php endif; ?>
						],function($){

							<?php if($expire <= 0)://Remove cookie when expire = 0 ?>
							$.removeCookie("<?php echo $cookie_name; ?>");
							<?php endif; ?>

							if($.cookie("<?php echo $cookie_name; ?>") == 'null' || $.cookie("<?php echo $cookie_name; ?>") != "true"){
									<?php if($open_popup_first): //Open popup on first load?>
										<?php if($delay && $delay>0): ?>
											setTimeout(showPopup<?php echo $id ?>,<?php echo $delay ?>);
										<?php else: ?>
											showPopup<?php echo $id ?>();
										<?php endif; ?>
									<?php endif; ?>

							}
					});
           });
        });

</script>
<?php } ?>