<?php
/*
* Ves Base Widget - Single image
*
* @package   vesbase
* @version   5.0
* @author    http://www.venustheme.com
* @copyright Copyright (C) October 2013 venustheme.com <@emai:venustheme@gmail.com>
*               <info@venustheme.com>.All rights reserved.
* @license   GNU General Public License version 2
*/
if($images):
$rad = rand();
//Popup Slideshow
$slideshow = $this->getConfig("slideshow", 0);
$slideshowSpeed = $this->getConfig("slideshow_speed", 2500);
$moduleId = "veswidgetgallery".rand().time();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$image_width = 60;
$image_height = 60;
$enable_collapse = $this->getConfig("enable_collapse", 0);
$auto_play_mode = $this->getConfig("auto_play", 0);
$interval = $this->getConfig("interval", 500);
$default_items = $this->getConfig("default_items", 4);
$portrait_items = $this->getConfig("portrait_items", 3);
$tablet_items = $this->getConfig("tablet_items", 2);
$tablet_small_items = $this->getConfig("tablet_small_items", 2);
$mobile_items = $this->getConfig("mobile_items", 1);
$large_items = $this->getConfig("large_items", 5);
$slideby = $this->getConfig("slideby", 1);
$dots = $this->getConfig('dots', true);
$nav = $this->getConfig('nav', true);
$nav_next = $this->getConfig('nav_next', '');
$nav_pre = $this->getConfig('nav_pre', '');
$nav_next_icon = $this->getConfig('nav_next_icon', 'fa fa-angle-right');
$nav_pre_icon = $this->getConfig('nav_pre_icon', 'fa fa-angle-left');
$rtl = $this->getConfig('rtl', false);
$loop = $this->getConfig('loop', false);

$show_info = $this->getConfig("show_info", 0);

$all_helper = $this->helper("Ves\All\Helper\Data");
?>
<div class="ves-widget widget-gallery-list block owlcarousel <?php echo $addition_cls; ?> <?php echo isset($stylecls)&&$stylecls?'block-'.$stylecls:'';?>">
    <?php if (isset($widget_heading)&&!empty($widget_heading)): ?>
        <div class="block-title">
            <?php if($enable_collapse): ?><span class="opener hidden-lg hidden-md" data-toggle="collapse" data-target="#widget-gallery-carousel<?php echo $moduleId; ?>"><i class="fa fa-angle-down"></i></span><?php endif; ?>
            <strong><span><?php echo $widget_heading; ?></span></strong>
        </div>
    <?php endif; ?>
    <div id="widget-gallery-carousel<?php echo $moduleId; ?>" class="widget-inner block-content <?php if($enable_collapse): ?> widget-enanle-collapse collapse in <?php endif; ?>">
        <div id="owlcarousel<?php echo $moduleId;?>" class="owl-carousel">
        <?php foreach( $images as $key => $image) :   ?>
            <div class="item <?php if($key==0) {?>first<?php } elseif($key == (count($images) -1 )) {?>last<?php } ?>">            
                <a class="group-file<?php echo $moduleId; ?> fancybox" href="<?php echo $image['imageURL'];?>" title="<?php echo $image['title'];?>" rel="group-gallery-<?php echo $moduleId; ?>">
                    <img src="<?php echo $image['thumbnailURL'];?>" alt="<?php echo $image['title'];?>"/>
                </a>
                <?php if($show_info && ($image['link'] || $image['title'] || $image['description'])): ?>
                    <div class="desc-gallery">
                        <div class="gallery-title">
                            <?php if($image['link']): ?>
                                <a href="<?php echo $image['link']; ?>"><?php echo $image['title'];?></a>
                            <?php else: ?>
                                <?php echo $image['title'];?>
                            <?php endif; ?>
                        </div>
                        <?php if($image['description']): ?>
                        <div class="gallery-description"><?php echo $image['description'];?></div>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>

            </div>
        <?php endforeach;?>
        </div>
    </div>
</div>
<div id="lookbook-products<?php echo $moduleId; ?>" style="display: none;">
<?php foreach ($images as $i => $image): ?>
    <?php if(isset($image['products']) && $image['products'] && count($image['products']) > 0): ?>
        <div class="owlcarousel">
            <div class="owl-products-carousel owl-carousel">
            <?php foreach($image['products'] as $_product): ?>
                 <?php $price_prefix = "lookbook_".$moduleId."_".rand().time(); ?>
                 <div class="item product-mini-item">
                    <div class="product-mini-info">
                        <div class="product-mini-image">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $block->escapeHtml($_product->getName()) ?>" class="product-image img">
                                <img class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($image_width,$image_height); ?>" width="<?php echo $image_width; ?>" height="<?php echo $image_height; ?>" alt="<?php echo $block->escapeHtml($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                            </a>
                        </div>
                        <div class="product-mini-info">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $block->escapeHtml($_product->getName()) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>

                            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>

                            <div class="price" >
                                <?php echo $this->getPriceHtml($_product, true, $price_prefix) ?>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
            </div>
        </div>
    <?php else: ?>
    <div style="display:none"></div>
    <?php endif; ?>
<?php endforeach; ?>
</div>
<?php if($enable_collapse): ?>
<script type="text/javascript">
require(['jquery'],function($){
    $(document).ready(function(){
    require([
        'jquery'
        <?php if($this->helper("Ves\All\Helper\Data")->getConfig("enable_bootstrap_js")): ?>
        ,"Ves_All/lib/bootstrap/js/bootstrap.min"
        <?php endif; ?>
        ],function($){
            
        });
    });
});
</script>
<?php endif; ?>
<script type="text/javascript">
require(['jquery'],function($){
            $(document).ready(function(){
                require([
                    'jquery'
                    <?php if($all_helper->getConfig("enable_owlcarousel")): ?>
                    ,"Ves_All/lib/owl.carousel/owl.carousel"
                    <?php endif; ?>
                    ],function($){
                        var widgetowlcarousel = jQuery('#owlcarousel<?php echo $moduleId;?>');
                            widgetowlcarousel.owlCarousel({
                                autoplay: <?php echo $auto_play_mode?'true':'false';?>,
                                autoplaySpeed: <?php echo $interval?(int)$interval:'500';?>,
                                autoplayHoverPause: true,
                                nav: <?php echo $nav?'true':'false';?>,
                                navText: ["<span class='<?php echo $nav_pre_icon; ?>'><?php echo $nav_pre; ?></span>","<span class='<?php echo $nav_next_icon; ?>'><?php echo $nav_next; ?></span>"],
                                slideBy: <?php echo (int)$slideby;?>,
                                loop: <?php echo $loop?'true':'false';?>,
                                margin: 0,
                                dots: <?php echo $dots?'true':'false';?>,
                                rtl: <?php echo $rtl?'true':'false';?>,
                                mouseDrag: true,
                                touchDrag: true,
                                autoWidth: false,
                                items: <?php echo $default_items?(int)$default_items:4; ?>,
                                <?php if($mobile_items || $tablet_small_items || $tablet_items || $portrait_items || $large_items): ?>
                                responsive: {
                                      <?php if($mobile_items): ?>
                                      0: {
                                            items: <?php echo $mobile_items?(int)$mobile_items:1; ?>
                                      },
                                      <?php endif; ?>
                                      <?php if($tablet_small_items): ?>
                                      600: {
                                            items: <?php echo $tablet_small_items?(int)$tablet_small_items:2; ?>
                                      },
                                      <?php endif; ?>
                                      <?php if($tablet_items): ?>
                                      767: {
                                            items: <?php echo $tablet_items?(int)$tablet_items:2; ?>
                                      },
                                      <?php endif; ?>
                                      <?php if($portrait_items): ?>
                                      1000: {
                                            items: <?php echo $portrait_items?(int)$portrait_items:3; ?>
                                      },
                                      <?php endif; ?>
                                      1200: {
                                            items: <?php echo $default_items?(int)$default_items:4; ?>
                                      },
                                      <?php if($large_items): ?>
                                      1900: {
                                            items: <?php echo $large_items?(int)$large_items:5; ?>
                                      }
                                      <?php endif; ?>
                                }
                                <?php endif; ?>
                            });
        });
            });
        });

</script>

<?php if ($ispopup): ?>
<script type="text/javascript">
require(['jquery'],function($){
        $(document).ready(function(){
    <?php if($popup_plugin == "colorbox"): ?>
        
        require([
        'jquery'
        <?php if($all_helper->getConfig("enable_colorbox")): ?>
        ,"Ves_All/lib/colorbox/jquery.colorbox.min"
        <?php endif; ?>
        ],function($){
            $(".group-file<?php echo $moduleId; ?>").colorbox({rel:'group-gallery-<?php echo $moduleId?>', overlayClose: true, opacity: 0.5, slideshow:<?php echo $slideshow?'true':'false'; ?>, slideshowSpeed: <?php echo (int)$slideshowSpeed; ?>});
        });
        
     <?php else: ?>
        require([
        'jquery'
        <?php if($all_helper->getConfig("enable_fancybox")): ?>
        ,"Ves_All/lib/fancybox/jquery.fancybox.pack"
        <?php endif; ?>
        <?php if($all_helper->getConfig("enable_fancybox_mousewell")): ?>
        ,"Ves_All/lib/fancybox/jquery.mousewheel-3.0.6.pack"
        <?php endif; ?>
        <?php if($all_helper->getConfig("enable_owlcarousel")): ?>
        ,"Ves_All/lib/owl.carousel/owl.carousel"
        <?php endif; ?>
        ],function($){
            jQuery(".group-file<?php echo $moduleId; ?>").fancybox({
                prevEffect      : 'none',
                nextEffect      : 'none',
                autoPlay        : <?php echo $slideshow?'true':'false'; ?>,
                playSpeed       : <?php echo (int)$slideshowSpeed; ?>,
                <?php if($use_custom_button): ?>
                closeBtn        : false,
                <?php endif; ?>
                helpers     : {
                    <?php if($use_custom_button): ?>
                    buttons : {},
                    <?php endif; ?>
                    <?php if($enable_thumb): ?>
                    thumbs  : {
                        width   : <?php echo (float)$popup_thumb_width; ?>,
                        height  : <?php echo (float)$popup_thumb_height; ?>
                    },
                    <?php endif; ?>
                    title   : { type : 'inside' }
                },
                afterShow: function() {
                    var list_products = jQuery("#lookbook-products<?php echo $moduleId; ?> > div").eq(this.index).html();
                    var customContent = "<div class='lookbook-products' style='display:none'><div class=\"lookbook-title\"><?php echo $block->escapeHtml('Lookbook'); ?></div>"+list_products+"</div>";

                    if(list_products) {
                        jQuery('.fancybox-overlay .fancybox-skin').first().append(customContent);
                        jQuery('.fancybox-overlay .lookbook-products').first().show();
                        
                        var productsowlcarousel = jQuery('.lookbook-products .owl-products-carousel').first();
                            productsowlcarousel.owlCarousel({
                                autoPlay: false,
                                slideSpeed: 500,
                                autoplayHoverPause: true,
                                navigationText: ["<span class='fa fa-angle-left'></span>","<span class='fa fa-angle-right'></span>"],
                                navigation: true,
                                autoWidth: false,
                                responsive: true,
                                items: 4
                            });
                    }
                }
            });
        });
     <?php endif; ?>
    });
});
</script>
<?php endif; ?>
<?php endif; ?>