<?php
$id = rand().time();
if (isset($tabs)): ?>
<div class="ves-widget widget-tab block <?php echo $addition_cls; ?> <?php if (isset($stylecls)&&$stylecls) echo 'block-'.$stylecls;?>">
	<?php if (isset($widget_heading)&&!empty($widget_heading)): ?>
	<div class="block-title">
		<strong><span><?php echo $widget_heading; ?></span></strong>
	</div>
	<?php endif; ?>
	<div class="widget-inner block-content items">	
		<div class="ves-widget-tab" data-mage-init='{"tabs":{"openedState":"active"}}'>
			<div class="tab-content">
			 	<?php foreach ($tabs as $key => $ac): ?>
			 		<div class="data item title"
                     aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $id.$key;?>-title"
                     data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $id.$key;?>">
	                    <a class="data switch"
	                       tabindex="-1"
	                       data-toggle="switch"
	                       href="#tab<?php /* @escapeNotVerified */ echo $id.$key; ?>"
	                       id="tab-label-<?php /* @escapeNotVerified */ echo $id.$key;?>-title">
	                        <?php echo $ac['header'];?>
	                    </a>
	                </div>
	                <div class="data item content" id="tab<?php /* @escapeNotVerified */ echo $id.$key; ?>" data-role="content">
	                    <?php echo $ac['content'];?>
	                </div>
			 	<?php endforeach; ?>
	 		</div>

		</div>
	</div>
</div>

<?php endif; ?>